name: run get_schedule.py
# Thanks: https://github.com/patrickloeber/python-github-action-template/blob/main/.github/workflows/actions.yml
on:
  schedule:
   - cron: '0 */6 * * *' # At 00:00 Every hour
   #- cron: '* * * * *' # every minute-- for testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install lxml
          pip install -r docs/requirements_schedule.txt

      - name: execute py script # run main.py
        #env:
          #SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python get_schedule.py
        
      - name: pull
        uses: ad-m/github-pull-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
 
      - name: commit files
        run: |
          git config --local user.email "jacobawinter@gmail.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update pool schedule" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
